### ISSUE TITLE
Option to print the number of comments found

### ISSUE THREAD

**Issue by pmcelhaney** [JohnPostlethwait/fixme#10]
So that we can track the numbers over time, it would be useful to have an output of the count of each type of issue.

```sh
$ fixme --count
00 BUG
01 FIXME
00 HACK
03 OPTIMIZE
02 NOTE
00 TODO
12 XXX
```

Also maybe a count of just the total.

```sh
$ fixme --count-total
18
```

Again, if you're interested, I'll send a PR.

**Comment by JohnPostlethwait** [comment]
Hi Patrick,

Sorry for the belated reply – I've been away on vacation. That feature sounds pretty great! I'd love a PR for that!

Thanks!
