### ISSUE TITLE
Update to isbinary breaks fixme

### ISSUE THREAD

**Issue by obartra** [JohnPostlethwait/fixme#12]
After the latest patch (0.4.1 vs 0.4.0) I get the following [error](https://circleci.com/gh/obartra/ssim/216):

```shell
/home/ubuntu/ssim/node_modules/isbinaryfile/index.js:21
                return cb(null, isBinaryCheck(bytes, size));
                       ^

TypeError: cb is not a function
    at /home/ubuntu/ssim/node_modules/isbinaryfile/index.js:21:24
    at /home/ubuntu/ssim/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

I believe it's related to the major version update for the `isbinaryfile` package [here](https://github.com/JohnPostlethwait/fixme/pull/11/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R37).

**Comment by JohnPostlethwait** [comment]
Ugh, sorry. Will issue an update shortly.

**Comment by JohnPostlethwait** [comment]
Update is released! Sorry for the issue: https://www.npmjs.com/package/fixme

**Comment by obartra** [comment]
Thanks for the quick response!
