### ISSUE TITLE
Forked repo with various enhancements 

### ISSUE THREAD

**Issue by ahmadassaf** [JohnPostlethwait/fixme#13]
I have forked this repo and tried to address various issues on https://github.com/ahmadassaf/code-notes

I hope you find this useful. 

I will be happy as well to edit the readme if you wish to include a link to it.

**Comment by JohnPostlethwait** [comment]
Why the fork?

You should have submitted a Pull Request...

**Comment by ahmadassaf** [comment]
to PR you need to fork @JohnPostlethwait. However, i have not created a PR since there are lots of structural changes in my fork that are beyond simple fixes.
