### ISSUE TITLE
Twig support?

### ISSUE THREAD

**Issue by jameelmoses** [JohnPostlethwait/fixme#16]
Passing `**/*.twig` generates no notes, even if the comments are in HTML format.

**Comment by jameelmoses** [comment]
```
gulp.task('notes', () => {
  fixme({
    file_patterns: ['**/*.js', '**/*.twig', '**/*.scss']
  });
});
```

**Comment by speaud** [comment]
Is there any update w.r.t @jameelmoses glob pattern comments?

**Comment by JohnPostlethwait** [comment]
Hi @speaud,

No, I'm not actively maintaining this package. I'm happy to accept pull requests and release new versions to address issues like this though.

**Comment by jameelmoses** [comment]
@JohnPostlethwait if you're looking for someone to take over maintaining the project, I'd be happy to.

**Comment by JohnPostlethwait** [comment]
Thanks, will reopen and take a look in a while here.

**Comment by jameelmoses** [comment]
Thanks!
