### ISSUE TITLE
Use camelCase instead of snake_case for options

### ISSUE THREAD

**Issue by kud** [JohnPostlethwait/fixme#26]
Hello,

I know it's a tricky issue but I think the options should be in camelCase (https://eslint.org/docs/rules/camelcase)

In JavaScript:

- lowerCamelCase for variables, properties, etc.
- UpperCamelCase for constructors.
- CAPITAL_CASE_WITH_UNDERSCORES for constants, which seem to be rarely used in JS anyway.

```
const fixme = require("fixme")

fixme({
  path: "./src/",
  ignored_directories: [],
  file_patterns: ["**/*"],
  file_encoding: "utf8",
  line_length_limit: 3000,
})
```

could be

```
const fixme = require("fixme")

fixme({
  path: "./src/",
  ignoredDirectories: [],
  filePatterns: ["**/*"],
  fileEncoding: "utf8",
  lineLengthLimit: 3000,
})
```

**Comment by jack-davidson** [comment]
I think this will just cause confusion. Also, programs rarely use camelCase for command line args.
