### ISSUE TITLE
Expanding filetypes

### ISSUE THREAD

**Issue by joshuadanpeterson** [JohnPostlethwait/fixme#31]
Currently the only supported filetypes are `**/*.js, Makefile, **/*.sh`. I opened a [pull request](https://github.com/JohnPostlethwait/fixme/pull/30) to expand the supported filetypes:

- **JavaScript**: `**/*.js`
- **Makefile**: `Makefile`
- **Shell scripts**: `**/*.sh`
- **HTML**: `**/*.html`
- **CSS**: `**/*.css`
- **JSON**: `**/*.json`
- **Markdown**: `**/*.md`
- **Text files**: `**/*.txt`
- **YAML**: `**/*.yaml`, `**/*.yml`
- **SASS**: `**/*.scss`
- **LESS**: `**/*.less`
- **PHP**: `**/*.php`
- **Java**: `**/*.java`
- **Python**: `**/*.py`
- **Ruby**: `**/*.rb`
- **C++**: `**/*.cpp`
- **C#**: `**/*.cs`
- **Swift**: `**/*.swift`
- **Rust**: `**/*.rs`
- **Go**: `**/*.go`
- **Header files**: `**/*.h`, `**/*.hpp`
- **TypeScript**: `**/*.ts`
- **JSX**: `**/*.jsx`
- **TSX**: `**/*.tsx`
- **Vue.js**: `**/*.vue`
- **Perl**: `**/*.pl`
- **Lua**: `**/*.lua`
- **Groovy**: `**/*.groovy`
- **Scala**: `**/*.scala`
- **Kotlin**: `**/*.kt`
- **Dart**: `**/*.dart`

**Comment by JohnPostlethwait** [comment]
Thanks @joshuadanpeterson! I appreciate the PR! Version 0.7.0 has been published with your changes and some security updates: https://www.npmjs.com/package/fixme/v/0.7.0

**Comment by joshuadanpeterson** [comment]
Thanks, @JohnPostlethwait, for the opportunity to contribute! Looking forward to using it with the new changes!
