### ISSUE TITLE
readdirp (dependency) has been upgraded to 2.0.0 any chance of upgrading

### ISSUE THREAD

**Issue by binduwavell** [JohnPostlethwait/fixme#8]
readdirp 1.1.0 uses rimraf 2.1.4 which uses graceful-fs 1.2.3. This version of graceful-fs will likely break with node 7 and up.

**Comment by JohnPostlethwait** [comment]
Eek, ok, thanks for letting me know! I'll try and get an update up soon.

**Comment by binduwavell** [comment]
I see you merged my PR with the updated deps, any chance you can push a release out to npm? Sorry to be a pest. I have a badge on some of my projects that shows the health of my deps, and this one dep causes that badge to be an ugly color ;)

I saw your comment in the readme that you aren't actively maintaining this. If necessary I can make a fork and use that, just figured it would be for the greater good to get this updated than to fragment (even just for myself) just for a dep dump... What do you think?

Thanks in advance,
-- Bindu

**Comment by JohnPostlethwait** [comment]
Hi Bindu,

Sorry for not doing that, the new version is up on NPM: https://www.npmjs.com/package/fixme (0.4.1)

I'm still happy to accept pull requests, as you have been doing, I'm just not working on it myself. I am also happy to release new versions based on the PRs (like your's) coming in, I just forgot to this time.

Hope this makes your life easier!

-John

**Comment by JohnPostlethwait** [comment]
Looks like this release broke the isBinaryFile usage. I released version 0.4.2 just now to fix it. Sorry if that messed you up at all.
