### ISSUE TITLE
Option to return error code when there are too many issues

### ISSUE THREAD

**Issue by pmcelhaney** [JohnPostlethwait/fixme#9]
I'm thinking about using fixme in a build script and having the build fail if there are too many items left unfixed.

It may be useful to have such a feature in the command line, e.g., if there more than 50 TODO/FIXME/etc. comments are found, exit with a non-zero status code.

```sh 
fixme --max=50
```

It could also be broken out into individual types. For example, say you want to be sure there are no more than 15 TODOs, 10 FIXMEs, and 20 overall. 

```sh 
fixme --max-TODO=15 --max-FIXME=10 --max=20
```

If you're interested, I'm happy to create a pull request.

**Comment by JohnPostlethwait** [comment]
That sounds useful, a PR would be great! Thanks for helping out!
